{{- if .Values.common.ghcrAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-io-secret
  namespace: {{ .Values.infraNamespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ required "common.ghcrAuth is required for Suivi-Item registry auth" .Values.common.ghcrAuth | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-io-secret
  namespace: {{ .Values.suiviItemNamespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ required "common.ghcrAuth is required for Suivi-Item registry auth" .Values.common.ghcrAuth | quote }}
{{- end }}
