{{- if .Values.common.ghcrAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-io-secret
  namespace: {{ .Values.infraNamespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"auth\":\"%s\"}}}" (printf "lucasduport:%s" .Values.common.ghcrAuth | b64enc) | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-io-secret
  namespace: {{ .Values.suiviItemNamespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"auth\":\"%s\"}}}" (printf "lucasduport:%s" .Values.common.ghcrAuth | b64enc) | quote }}
{{- end }}
