caddy:
  secrets:
    CLOUDFLARE_API_TOKEN: "<YOUR_CLOUDFLARE_API_TOKEN>"
    NAS_TARGET: "<YOUR_NAS_IP_OR_HOSTNAME>"

gatus:
  secrets:
    DISCORD_WEBHOOK_ALL: "<YOUR_DISCORD_WEBHOOK_URL>"
    DISCORD_WEBHOOK_TV: "<YOUR_DISCORD_WEBHOOK_URL_TV>"

lldap:
  secrets:
    LLDAP_JWT_SECRET: "<GENERATE_RANDOM_JWT_SECRET>"
    LLDAP_KEY_SEED: "<GENERATE_RANDOM_KEY_SEED>"
    LLDAP_LDAP_USER_PASS: "<YOUR_LDAP_ADMIN_PASSWORD>"

streamShare:
  secrets:
    POSTGRES_DB: "streamshare"
    POSTGRES_USER: "streamshare"
    POSTGRES_PASSWORD: "<YOUR_POSTGRES_DB_PASSWORD>"

vpn:
  secrets:
    WG_HOST: "vpn.lucasduport.cc"
    PASSWORD_HASH: "<YOUR_BCRYPT_HASH_HERE>"
    WG_ENABLE_IPV6: "false"

vaultwarden:
  secrets:
    ADMIN_TOKEN: "<YOUR_VAULTWARDEN_ADMIN_TOKEN>"
    PUSH_INSTALLATION_ID: "<YOUR_PUSH_INSTALLATION_ID>"
    PUSH_INSTALLATION_KEY: "<YOUR_PUSH_INSTALLATION_KEY>"

suiviItem:
  secrets:
    SECRET_KEY: "<YOUR_FLASK_SECRET_KEY>"
