# Development overrides for infra-stack.
infraNamespace: infra-dev
suiviItemNamespace: suivi-item-dev

ingressDomain: lucasduport.cc
subdomainPrefix: "dev-"
isDev: true

caddy:
  httpPort: 8080
  httpsPort: 8443
