services:
  db:
    image: postgres:16-alpine
    container_name: shlink_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - shlink_db:/var/lib/postgresql/data
    restart: unless-stopped

  shlink:
    image: shlinkio/shlink:stable
    container_name: shlink
    depends_on:
      - db
    environment:
      TZ: Europe/Paris
      SHORT_DOMAIN_HOST: sh.lucasduport.cc
      SHORT_DOMAIN_SCHEMA: https
      DB_DRIVER: postgres
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      SHORT_URL_LENGTH: 5
      MIN_SHORTCODE_LENGTH: 5
      MAX_SHORTCODE_LENGTH: 10
    restart: unless-stopped
    networks:
      - shlink_net
    expose:
      - "8080" # internal only (not mapped to host)

  shlink-web:
    image: shlinkio/shlink-web-client:stable
    container_name: shlink_web
    environment:
      # You can leave these blank and configure in the UI if you prefer
      SHLINK_SERVER_URL: http://shlink:8080
      SHLINK_SERVER_API_KEY: ${SHLINK_API_KEY}
    ports:
      - "8092:80"   # expose only web UI
    depends_on:
      - shlink
    restart: unless-stopped
    networks:
      - shlink_net

volumes:
  shlink_db:

networks:
  shlink_net:
    driver: bridge
