# Docs: https://github.com/TwiN/gatus

metrics: true

storage:
  type: sqlite
  path: /data/data.db

alerting:
  # Discord alerting
  discord:
    # Webhook for ALL endpoints' unhealthy alerts
    webhook-url: ${DISCORD_WEBHOOK_ALL}
    default-alert:
      failure-threshold: 1
      success-threshold: 1
      send-on-resolved: true
      description: "Endpoint unhealthy"

  # Placeholder example; wire to your notifier later if desired
  slack:
    webhook-url: ""
    default-alert:
      enabled: false

ui:
  header: "let's see if something is broken"
  title: "Status | let's see if something is broken"

endpoints:
  - name: "TrueNAS Dashboard"
    group: public
    url: https://truenas.lucasduport.cc/
    interval: 1m
    conditions:
      - '[STATUS] < 400'
    alerts:
      - type: discord

  - name: "LDAP Dashboard"
    group: public
    url: https://lldap.lucasduport.cc/
    interval: 1m
    conditions:
      - '[STATUS] < 400'
    alerts:
      - type: discord

  - name: "TV"
    group: public
    url: tcp://tv.lucasduport.cc:443
    interval: 1m
    conditions:
      - '[CONNECTED] == true'
    alerts:
      # TV-specific webhook (both failure and resolved)
      - type: discord
        description: "TV endpoint status"
        send-on-resolved: true
        provider-override:
          webhook-url: ${DISCORD_WEBHOOK_TV}
      # Global webhook for any unhealthy endpoints
      - type: discord

  - name: "Portfolio"
    group: public
    url: https://portfolio.lucasduport.cc/
    interval: 1m
    conditions:
      - '[STATUS] >= 200'
      - '[STATUS] < 400'
    alerts:
      - type: discord

  - name: "Redirect English resume"
    group: public
    url: https://resume.lucasduport.cc/
    interval: 5m
    conditions:
      - '[STATUS] >= 200'
      - '[STATUS] < 400'
    alerts:
      - type: discord

  - name: "Redirect French resume"
    group: public
    url: https://cv.lucasduport.cc/
    interval: 5m
    conditions:
      - '[STATUS] >= 200'
      - '[STATUS] < 400'
    alerts:
      - type: discord

  - name: "Redirect portfolio"
    group: public
    url: https://lucasduport.cc/
    interval: 1m
    conditions:
      - '[STATUS] >= 200'
      - '[STATUS] < 400'
    alerts:
      - type: discord

  - name: "Redirect on www"
    group: public
    url: https://www.lucasduport.cc/
    interval: 1m
    conditions:
      - '[STATUS] >= 200'
      - '[STATUS] < 400'
    alerts:
      - type: discord
