{{- if .Values.lldap.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: lldap-secrets
  namespace: {{ .Values.infraNamespace }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
    app: lldap
type: Opaque
stringData:
  {{- toYaml .Values.lldap.secrets | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: lldap
  namespace: {{ .Values.infraNamespace }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
    app: lldap
spec:
  type: ClusterIP
  selector:
    app: lldap
  ports:
    - name: ldap
      port: 3890
      targetPort: 3890
      protocol: TCP
    - name: web
      port: 17170
      targetPort: 17170
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lldap
  namespace: {{ .Values.infraNamespace }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
    app: lldap
spec:
  serviceName: lldap
  replicas: {{ .Values.lldap.replicas }}
  selector:
    matchLabels:
      app: lldap
  template:
    metadata:
      labels:
        app: lldap
    spec:
      {{- with .Values.lldap.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: lldap
          image: {{ .Values.lldap.image }}
          ports:
            - name: ldap
              containerPort: 3890
              protocol: TCP
            - name: web
              containerPort: 17170
              protocol: TCP
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: LLDAP_LDAP_BASE_DN
              value: {{ .Values.lldap.baseDN | quote }}
            - name: LLDAP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lldap-secrets
                  key: LLDAP_JWT_SECRET
            - name: LLDAP_KEY_SEED
              valueFrom:
                secretKeyRef:
                  name: lldap-secrets
                  key: LLDAP_KEY_SEED
            - name: LLDAP_LDAP_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: lldap-secrets
                  key: LLDAP_LDAP_USER_PASS
          volumeMounts:
            - name: lldap-data
              mountPath: /data
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 17170
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 17170
            initialDelaySeconds: 15
            periodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: lldap-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
{{- end }}
